# Generated by Django 2.2.8 on 2019-12-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='category',
            new_name='categorys',
        ),
    ]
