# Generated by Django 2.2.8 on 2019-12-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0002_auto_20191210_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.SmallIntegerField(default=0, help_text='排序，越大越靠前'),
        ),
    ]
