# Generated by Django 2.2.8 on 2019-12-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0003_category_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default=0, help_text='主分类', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='webstack.Category'),
        ),
    ]
