# Generated by Django 2.2.8 on 2019-12-10 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0004_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='主分类', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='webstack.Category'),
        ),
    ]
