# Generated by Django 2.2.8 on 2019-12-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0005_auto_20191211_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='linecons-star', help_text='图标', max_length=30),
        ),
    ]
