# Generated by Django 2.2.8 on 2019-12-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0006_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='图标', max_length=30, null=True),
        ),
    ]
